### ISSUE TITLE
Import error 'authlib' and 'dotenv'

### ISSUE THREAD

**Issue by ejshakman** [CS322-SP23/MixMaster#37]
After changing `SERVER_NAME` in 'helper.py', I opened the app in Browser and got a NoAppException with the following details:

_ModuleNotFoundError_ for `authlib`, which stems from two unresolved imports in ['authentication.py'](https://github.com/CS322-SP23/MixMaster/blob/b9e4f902de690f095ef76ee8423a12924aff4ac1/authentication.py#L5-L6) and one unresolved import in ['app.py'](https://github.com/CS322-SP23/MixMaster/blob/b9e4f902de690f095ef76ee8423a12924aff4ac1/app.py#L4).

_ModuleNotFoundError_ for `dotenv`, which stems from one unresolved import in ['app.py'](https://github.com/CS322-SP23/MixMaster/blob/b9e4f902de690f095ef76ee8423a12924aff4ac1/app.py#L5).

**Comment by hjwebb01** [comment]
Updated comments
